title: "Brick's Blog"
author: "0x1F9F1"
description: > # this means to ignore newlines until "baseurl:"
  The blog of 0x1F9F1

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  "0x1F9F1" # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
