title: "Brick's Blog"

description: > # this means to ignore newlines until "baseurl:"
  The blog of 0x1F9F1

# social links
github_username:  "0x1F9F1" # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
